### ISSUE TITLE
[meta] new release (0.3.1.0 mentioned in changelog) isn't in releases

### ISSUE THREAD

**Issue by bootmii** [Dn-Programming-Core-Management/Dn-FamiTracker#70]
You intended to make a new release three days ago, but it's not on the releases page.

**Comment by Gumball2415** [comment]
the changelog regarding upcoming releases should be considered beta. i would rather update the changelog every now and then with 10 commits to log rather than update it just before release with 50+ commits to log. as a side note, i will clarify this in the future by writing "beta" or "unreleased" next to the version number.
