### ISSUE TITLE
[INFO] Deprecating Windows XP Support

### ISSUE THREAD

**Issue by N-SPC700** [Dn-Programming-Core-Management/Dn-FamiTracker#82]
Due to updates to Visual Code 2019, Dn-FamiTracker will be dropping Windows XP support for all new releases of Dn-FamiTracker. 

While this may be sad to hear for some, we really can't keep supporting a deprecated operating system that is 7 years past it's extended support lifespan. 

Despite this, the latest version as of writing (release 0.3.1.0) still supports XP. Consider this build the "legacy" compatible build for older systems. With the release of the next Dn version, 0.3.1.0 will be effectively "legacy" and/or deprecated. When 0.3.1.0 becomes obsolete, it too will become deprecated, and any bugs in that build _will not_ get fixed unless it also affects all later builds of Dn-FamiTracker.

**Comment by nyanpasu64** [comment]
I plan to create a Windows XP branch or fork, and cherry-pick fixes for critical issues like module corruption due to missing fsync, and republish Appveyor builds as binary releases. I do not plan to cherry-pick feature additions. The main repository _may_ stop compiling with v141_xp (VS2017 compiler in Windows XP mode) at some point in the future.

Is there a plan to switch to the v142 compiler and Windows 10 SDK?
